### ISSUE TITLE
missing some theme __.xbf files

### ISSUE THREAD

**Issue by alexander-ziegler-simonsen** [gave92/CalendarControl#1]
I have been trying to use your calendar controller, on a project I am doing from my school.

I added by the nugget installer, then I had to install these packages, before I got it to almost work:
- System.Reactive.Core
- System.Reactive.Linq
- System.Reactive.Windows.Threading

After you drag and drop the controller onto the view, it always showed a error, saying "Value cannot be null (parameter name: dispatcher)" 

I was trying to make a view model (MVVM), that could be connected to it, but after I made it, I got 5 new errors (see the photo):
- Error Payload file 'C:\Users\ziegler\.nuget\packages\gave.libs.calendarcontrol\0.2.3\ref\uap10.0\CalendarControl\Themes\Calendar.xbf' does not exist.	WorkPlanner			
- Error Payload file 'C:\Users\ziegler\.nuget\packages\gave.libs.calendarcontrol\0.2.3\ref\uap10.0\CalendarControl\Themes\EventItem.xbf' does not exist.	WorkPlanner	
- Error Payload file 'C:\Users\ziegler\.nuget\packages\gave.libs.calendarcontrol\0.2.3\ref\uap10.0\CalendarControl\Themes\EventView.xbf' does not exist.	WorkPlanner	
- Error Payload file 'C:\Users\ziegler\.nuget\packages\gave.libs.calendarcontrol\0.2.3\ref\uap10.0\CalendarControl\Themes\DayView.xbf' does not exist.	WorkPlanner	
- Error Payload file 'C:\Users\ziegler\.nuget\packages\gave.libs.calendarcontrol\0.2.3\ref\uap10.0\CalendarControl\Themes\Generic.xbf' does not exist.	WorkPlanner	

I tried to add the xaml files (from the theme folder) in that folder path, but that did nothing.

I hope to hear from you, before this Friday this week (since I need to deliver my project that day)

- photo of the errors in visual studio
![errors](https://user-images.githubusercontent.com/29373163/49745815-190c3f00-fca0-11e8-9ffb-4fb8bb769912.PNG)

- photo of the installed nuggets
![nuget](https://user-images.githubusercontent.com/29373163/49745816-19a4d580-fca0-11e8-8367-8a5030a920d0.PNG)

- the folders where the missing files should be in (the 'show hidden files' is on)
![theme folder](https://user-images.githubusercontent.com/29373163/49745817-19a4d580-fca0-11e8-9cf0-0f10123da679.PNG)

**Comment by gave92** [comment]
Hello, version 0.2.4 of the package should fix the issue. Let me know and thanks for reporting this!
